/** @type {import('tailwindcss').Config} */
module.exports = {
  // Chỉ định các file sẽ sử dụng Tailwind classes
  content: ["./src/app/**/*.{js,jsx,ts,tsx}", "./src/components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: '#f7faf8',
        'surface-dim': '#d7dbd9',
        'surface-bright': '#f7faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f3',
        'surface-container': '#ebefed',
        'surface-container-high': '#e5e9e7',
        'surface-container-highest': '#e0e3e1',
        'on-surface': '#181c1c',
        'on-surface-variant': '#3e4947',
        'inverse-surface': '#2d3130',
        'inverse-on-surface': '#eef1f0',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',
        'surface-tint': '#006a63',
        primary: '#005c55',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'on-primary-container': '#a3faef',
        'inverse-primary': '#80d5cb',
        secondary: '#545f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        tertiary: '#425268',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5a6a81',
        'on-tertiary-container': '#deeaff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#9cf2e8',
        'primary-fixed-dim': '#80d5cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        'secondary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary-fixed': '#111c2d',
        'on-secondary-fixed-variant': '#3c475a',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        background: '#f7faf8',
        'on-background': '#181c1c',
        'surface-variant': '#e0e3e1',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        display: '34px',
        'headline-lg': '28px',
        'headline-md': '22px',
        'title-lg': '20px',
        'body-lg': '17px',
        'body-md': '15px',
        'label-md': '13px',
        'label-sm': '11px',
      },
      fontWeight: {
        display: '700',
        'headline-lg': '700',
        'headline-md': '600',
        'title-lg': '600',
        'body-lg': '400',
        'body-md': '400',
        'label-md': '500',
        'label-sm': '600',
      },
      lineHeight: {
        display: '41px',
        'headline-lg': '34px',
        'headline-md': '28px',
        'title-lg': '25px',
        'body-lg': '22px',
        'body-md': '20px',
        'label-md': '18px',
        'label-sm': '13px',
      },
      letterSpacing: {
        display: '-0.02em',
        'headline-lg': '-0.01em',
        'label-md': '0.01em',
        'label-sm': '0.06em',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'margin-mobile': '20px',
        'gutter-mobile': '12px',
      },
    },
  },
  plugins: [],
}
