/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: '#f7faf8',
        'surface-dim': '#d7dbd9',
        'surface-bright': '#f7faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f3',
        'surface-container': '#ebefed',
        'surface-container-high': '#e5e9e7',
        'surface-container-highest': '#e0e3e1',
        'on-surface': '#181c1c',
        'on-surface-variant': '#3e4947',
        'inverse-surface': '#2d3130',
        'inverse-on-surface': '#eef1f0',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',
        'surface-tint': '#006a63',
        primary: '#005c55',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'on-primary-container': '#a3faef',
        'inverse-primary': '#80d5cb',
        secondary: '#545f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        tertiary: '#425268',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5a6a81',
        'on-tertiary-container': '#deeaff',
        'surface-variant': '#e0e3e1',
        background: '#f7faf8',
      },
      spacing: {
        'margin-mobile': '20px',
        'gutter-mobile': '12px',
      },
    },
  },
  plugins: [],
};
