// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { AiStylist, Authentication, Closet__AiScanner, Dashboard__Recommendation, Default, type Options } from '../sdk.gen';
import type { ApproveAndSaveItemApiV1ClosetSavePostData, ApproveAndSaveItemApiV1ClosetSavePostError, ChatAndModifyOutfitApiV1AiChatPostData, ChatAndModifyOutfitApiV1AiChatPostError, ChatAndModifyOutfitApiV1AiChatPostResponse, GetHomeDashboardApiV1DashboardHomeGetData, GetHomeDashboardApiV1DashboardHomeGetError, GetHomeDashboardApiV1DashboardHomeGetResponse, GetMyWardrobeApiV1ClosetItemsGetData, GetMyWardrobeApiV1ClosetItemsGetError, GetMyWardrobeApiV1ClosetItemsGetResponse, GetOutfitFromItemsApiV1AiOutfitFromItemsPostData, GetOutfitFromItemsApiV1AiOutfitFromItemsPostError, GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponse, GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetData, GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetError, GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponse, GetStyleSuggestionsApiV1AiStyleSuggestionsGetData, GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponse, GetSwapAlternativesApiV1DashboardSwapAlternativesGetData, GetSwapAlternativesApiV1DashboardSwapAlternativesGetError, GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponse, GetWardrobeStyleInsightsApiV1DashboardInsightsGetData, GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponse, GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetData, GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponse, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostError, LoginApiV1AuthLoginPostResponse, LogoutApiV1AuthLogoutPostData, ReadRootGetData, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostError, RegisterApiV1AuthRegisterPostResponse, ScanClothingCameraApiV1ClosetScanPostData, ScanClothingCameraApiV1ClosetScanPostError, ScanClothingCameraApiV1ClosetScanPostResponse, SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData, SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostError, WearOutfitApiV1DashboardWearOutfitPostData, WearOutfitApiV1DashboardWearOutfitPostError } from '../types.gen';

/**
 * Register
 *
 * API Đăng ký tài khoản mới từ màn hình Onboarding
 */
export const registerApiV1AuthRegisterPostMutation = (options?: Partial<Options<RegisterApiV1AuthRegisterPostData>>): UseMutationOptions<RegisterApiV1AuthRegisterPostResponse, AxiosError<RegisterApiV1AuthRegisterPostError>, Options<RegisterApiV1AuthRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterApiV1AuthRegisterPostResponse, AxiosError<RegisterApiV1AuthRegisterPostError>, Options<RegisterApiV1AuthRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.registerApiV1AuthRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 *
 * API Đăng nhập chuẩn OAuth2, trả về Bearer Token cho Mobile
 */
export const loginApiV1AuthLoginPostMutation = (options?: Partial<Options<LoginApiV1AuthLoginPostData>>): UseMutationOptions<LoginApiV1AuthLoginPostResponse, AxiosError<LoginApiV1AuthLoginPostError>, Options<LoginApiV1AuthLoginPostData>> => {
    const mutationOptions: UseMutationOptions<LoginApiV1AuthLoginPostResponse, AxiosError<LoginApiV1AuthLoginPostError>, Options<LoginApiV1AuthLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.loginApiV1AuthLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 *
 * API Đăng xuất: Đưa JWT Token hiện tại vào Blacklist của Redis để hủy hiệu lực
 */
export const logoutApiV1AuthLogoutPostMutation = (options?: Partial<Options<LogoutApiV1AuthLogoutPostData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<LogoutApiV1AuthLogoutPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<LogoutApiV1AuthLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Authentication.logoutApiV1AuthLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHomeDashboardApiV1DashboardHomeGetQueryKey = (options: Options<GetHomeDashboardApiV1DashboardHomeGetData>) => createQueryKey('getHomeDashboardApiV1DashboardHomeGet', options);

/**
 * Get Home Dashboard
 *
 * API chính cho Màn hình 2 - Dashboard
 */
export const getHomeDashboardApiV1DashboardHomeGetOptions = (options: Options<GetHomeDashboardApiV1DashboardHomeGetData>) => queryOptions<GetHomeDashboardApiV1DashboardHomeGetResponse, AxiosError<GetHomeDashboardApiV1DashboardHomeGetError>, GetHomeDashboardApiV1DashboardHomeGetResponse, ReturnType<typeof getHomeDashboardApiV1DashboardHomeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Dashboard__Recommendation.getHomeDashboardApiV1DashboardHomeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHomeDashboardApiV1DashboardHomeGetQueryKey(options)
});

/**
 * Wear Outfit
 *
 * Bấm 'Wear This Outfit' -> Lưu vào lịch sử đồ mặc trong ngày (Screen 6)
 */
export const wearOutfitApiV1DashboardWearOutfitPostMutation = (options?: Partial<Options<WearOutfitApiV1DashboardWearOutfitPostData>>): UseMutationOptions<unknown, AxiosError<WearOutfitApiV1DashboardWearOutfitPostError>, Options<WearOutfitApiV1DashboardWearOutfitPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<WearOutfitApiV1DashboardWearOutfitPostError>, Options<WearOutfitApiV1DashboardWearOutfitPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Dashboard__Recommendation.wearOutfitApiV1DashboardWearOutfitPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSwapAlternativesApiV1DashboardSwapAlternativesGetQueryKey = (options: Options<GetSwapAlternativesApiV1DashboardSwapAlternativesGetData>) => createQueryKey('getSwapAlternativesApiV1DashboardSwapAlternativesGet', options);

/**
 * Get Swap Alternatives
 *
 * API cho Screen 3 - Slide-up Bottom Sheet chọn đồ thay thế phù hợp thời tiết
 */
export const getSwapAlternativesApiV1DashboardSwapAlternativesGetOptions = (options: Options<GetSwapAlternativesApiV1DashboardSwapAlternativesGetData>) => queryOptions<GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponse, AxiosError<GetSwapAlternativesApiV1DashboardSwapAlternativesGetError>, GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponse, ReturnType<typeof getSwapAlternativesApiV1DashboardSwapAlternativesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Dashboard__Recommendation.getSwapAlternativesApiV1DashboardSwapAlternativesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSwapAlternativesApiV1DashboardSwapAlternativesGetQueryKey(options)
});

export const getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetQueryKey = (options?: Options<GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetData>) => createQueryKey('getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGet', options);

/**
 * Get Weekly Calendar Strip
 *
 * API cho Screen 6 (Phần Top): Lấy chuỗi lịch 7 ngày trong tuần hiện tại.
 * Trả về danh sách các ngày từ Thứ 2 đến Chủ Nhật kèm Outfit đã xếp lịch.
 */
export const getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetOptions = (options?: Options<GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetData>) => queryOptions<GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponse, AxiosError<DefaultError>, GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponse, ReturnType<typeof getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Dashboard__Recommendation.getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetQueryKey(options)
});

export const getWardrobeStyleInsightsApiV1DashboardInsightsGetQueryKey = (options?: Options<GetWardrobeStyleInsightsApiV1DashboardInsightsGetData>) => createQueryKey('getWardrobeStyleInsightsApiV1DashboardInsightsGet', options);

/**
 * Get Wardrobe Style Insights
 *
 * API cho Screen 6 (Phần Bottom Section): Tính toán dữ liệu cho Ring Chart đồ họa.
 * Công thức Tỷ lệ sử dụng = (Số món đồ đã từng mặc trong tháng / Tổng số đồ trong tủ) * 100
 */
export const getWardrobeStyleInsightsApiV1DashboardInsightsGetOptions = (options?: Options<GetWardrobeStyleInsightsApiV1DashboardInsightsGetData>) => queryOptions<GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponse, AxiosError<DefaultError>, GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponse, ReturnType<typeof getWardrobeStyleInsightsApiV1DashboardInsightsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Dashboard__Recommendation.getWardrobeStyleInsightsApiV1DashboardInsightsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWardrobeStyleInsightsApiV1DashboardInsightsGetQueryKey(options)
});

/**
 * Sync Offline History
 *
 * API đặc thù cho Mobile: Nhận một loạt các hành động mặc đồ
 * được lưu tạm dưới máy user khi họ bị mất mạng (Offline Mode).
 */
export const syncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostMutation = (options?: Partial<Options<SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData>>): UseMutationOptions<unknown, AxiosError<SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostError>, Options<SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostError>, Options<SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Dashboard__Recommendation.syncOfflineHistoryApiV1DashboardSyncOfflineHistoryPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Scan Clothing Camera
 *
 * Bước 1: Mobile chụp ảnh gửi lên -> Đẩy ngay việc vào Redis Queue cho Worker xử lý ngầm.
 * Phản hồi ngay lập tức sau vài mili-giây để Mobile hiển thị hiệu ứng quét techy.
 */
export const scanClothingCameraApiV1ClosetScanPostMutation = (options?: Partial<Options<ScanClothingCameraApiV1ClosetScanPostData>>): UseMutationOptions<ScanClothingCameraApiV1ClosetScanPostResponse, AxiosError<ScanClothingCameraApiV1ClosetScanPostError>, Options<ScanClothingCameraApiV1ClosetScanPostData>> => {
    const mutationOptions: UseMutationOptions<ScanClothingCameraApiV1ClosetScanPostResponse, AxiosError<ScanClothingCameraApiV1ClosetScanPostError>, Options<ScanClothingCameraApiV1ClosetScanPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Closet__AiScanner.scanClothingCameraApiV1ClosetScanPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getScanTaskStatusApiV1ClosetScanStatusTaskIdGetQueryKey = (options: Options<GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetData>) => createQueryKey('getScanTaskStatusApiV1ClosetScanStatusTaskIdGet', options);

/**
 * Get Scan Task Status
 *
 * Bước 2: Mobile thỉnh thoảng gọi lại API này (cứ 1 giây/lần) để kiểm tra xem AI chạy xong chưa.
 */
export const getScanTaskStatusApiV1ClosetScanStatusTaskIdGetOptions = (options: Options<GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetData>) => queryOptions<GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponse, AxiosError<GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetError>, GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponse, ReturnType<typeof getScanTaskStatusApiV1ClosetScanStatusTaskIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Closet__AiScanner.getScanTaskStatusApiV1ClosetScanStatusTaskIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScanTaskStatusApiV1ClosetScanStatusTaskIdGetQueryKey(options)
});

/**
 * Approve And Save Item
 *
 * Bước 3: User nhìn thấy các tag gợi ý trên màn hình Bottom 1/3, bấm "Approve & Save".
 * Backend chính thức lưu món đồ sạch nền này vào tủ đồ Postgres.
 */
export const approveAndSaveItemApiV1ClosetSavePostMutation = (options?: Partial<Options<ApproveAndSaveItemApiV1ClosetSavePostData>>): UseMutationOptions<unknown, AxiosError<ApproveAndSaveItemApiV1ClosetSavePostError>, Options<ApproveAndSaveItemApiV1ClosetSavePostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<ApproveAndSaveItemApiV1ClosetSavePostError>, Options<ApproveAndSaveItemApiV1ClosetSavePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Closet__AiScanner.approveAndSaveItemApiV1ClosetSavePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMyWardrobeApiV1ClosetItemsGetQueryKey = (options?: Options<GetMyWardrobeApiV1ClosetItemsGetData>) => createQueryKey('getMyWardrobeApiV1ClosetItemsGet', options);

/**
 * Get My Wardrobe
 *
 * API cho Screen 4 (My Wardrobe Screen): Lấy toàn bộ tủ đồ phẳng, hỗ trợ filter pill và phân trang
 */
export const getMyWardrobeApiV1ClosetItemsGetOptions = (options?: Options<GetMyWardrobeApiV1ClosetItemsGetData>) => queryOptions<GetMyWardrobeApiV1ClosetItemsGetResponse, AxiosError<GetMyWardrobeApiV1ClosetItemsGetError>, GetMyWardrobeApiV1ClosetItemsGetResponse, ReturnType<typeof getMyWardrobeApiV1ClosetItemsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Closet__AiScanner.getMyWardrobeApiV1ClosetItemsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMyWardrobeApiV1ClosetItemsGetQueryKey(options)
});

export const getStyleSuggestionsApiV1AiStyleSuggestionsGetQueryKey = (options?: Options<GetStyleSuggestionsApiV1AiStyleSuggestionsGetData>) => createQueryKey('getStyleSuggestionsApiV1AiStyleSuggestionsGet', options);

/**
 * Get Style Suggestions
 *
 * API Gợi ý style (AI): Phân tích tủ đồ của người dùng và style yêu thích để đưa ra lời khuyên thời trang.
 */
export const getStyleSuggestionsApiV1AiStyleSuggestionsGetOptions = (options?: Options<GetStyleSuggestionsApiV1AiStyleSuggestionsGetData>) => queryOptions<GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponse, AxiosError<DefaultError>, GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponse, ReturnType<typeof getStyleSuggestionsApiV1AiStyleSuggestionsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await AiStylist.getStyleSuggestionsApiV1AiStyleSuggestionsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStyleSuggestionsApiV1AiStyleSuggestionsGetQueryKey(options)
});

/**
 * Get Outfit From Items
 *
 * API Gợi ý outfit từ 1 hoặc vài món đồ (AI): Chọn trước các món đồ, AI sẽ phối thêm các đồ khác để hoàn thiện set đồ.
 */
export const getOutfitFromItemsApiV1AiOutfitFromItemsPostMutation = (options?: Partial<Options<GetOutfitFromItemsApiV1AiOutfitFromItemsPostData>>): UseMutationOptions<GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponse, AxiosError<GetOutfitFromItemsApiV1AiOutfitFromItemsPostError>, Options<GetOutfitFromItemsApiV1AiOutfitFromItemsPostData>> => {
    const mutationOptions: UseMutationOptions<GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponse, AxiosError<GetOutfitFromItemsApiV1AiOutfitFromItemsPostError>, Options<GetOutfitFromItemsApiV1AiOutfitFromItemsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AiStylist.getOutfitFromItemsApiV1AiOutfitFromItemsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Chat And Modify Outfit
 *
 * API Yêu cầu hoặc sửa style/outfit bằng text giống phiên chat (AI).
 * Nhận vào tin nhắn yêu cầu thay đổi trang phục hiện tại hoặc đề xuất set đồ mới.
 */
export const chatAndModifyOutfitApiV1AiChatPostMutation = (options?: Partial<Options<ChatAndModifyOutfitApiV1AiChatPostData>>): UseMutationOptions<ChatAndModifyOutfitApiV1AiChatPostResponse, AxiosError<ChatAndModifyOutfitApiV1AiChatPostError>, Options<ChatAndModifyOutfitApiV1AiChatPostData>> => {
    const mutationOptions: UseMutationOptions<ChatAndModifyOutfitApiV1AiChatPostResponse, AxiosError<ChatAndModifyOutfitApiV1AiChatPostError>, Options<ChatAndModifyOutfitApiV1AiChatPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await AiStylist.chatAndModifyOutfitApiV1AiChatPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readRootGetQueryKey = (options?: Options<ReadRootGetData>) => createQueryKey('readRootGet', options);

/**
 * Read Root
 */
export const readRootGetOptions = (options?: Options<ReadRootGetData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof readRootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Default.readRootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRootGetQueryKey(options)
});
