// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * AIChatRequest
 */
export type AiChatRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * History
     */
    history?: Array<ChatMessage> | null;
    /**
     * Current Outfit Id
     */
    current_outfit_id?: number | null;
    /**
     * Event
     */
    event?: string | null;
    /**
     * Weather
     */
    weather?: string | null;
};

/**
 * AIChatResponse
 */
export type AiChatResponse = {
    /**
     * Reply
     */
    reply: string;
    /**
     * Reply Text
     */
    reply_text?: string | null;
    suggested_outfit?: OutfitRecommendation | null;
    /**
     * Recommended Outfit
     */
    recommended_outfit?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ApproveAndSaveRequest
 */
export type ApproveAndSaveRequest = {
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Category
     */
    category: string;
    /**
     * Color Name
     */
    color_name?: string | null;
    /**
     * Color Code
     */
    color_code: string;
    /**
     * Style Tag
     */
    style_tag: string;
    /**
     * Is Ai Fixed
     */
    is_ai_fixed?: boolean | null;
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_scan_clothing_camera_api_v1_closet_scan_post
 */
export type BodyScanClothingCameraApiV1ClosetScanPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_avatar_api_v1_auth_profile_avatar_post
 */
export type BodyUploadAvatarApiV1AuthProfileAvatarPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_clothing_item_image_api_v1_closet_items_upload_post
 */
export type BodyUploadClothingItemImageApiV1ClosetItemsUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CalendarDayPreview
 */
export type CalendarDayPreview = {
    /**
     * Date
     */
    date: string;
    /**
     * Day Name
     */
    day_name: string;
    /**
     * Is Highlighted
     */
    is_highlighted: boolean;
    /**
     * Event Title
     */
    event_title?: string | null;
    outfit?: OutfitRecommendation | null;
};

/**
 * CalendarForecastDay
 */
export type CalendarForecastDay = {
    /**
     * Date
     */
    date: string;
    /**
     * Temp C
     */
    temp_c: number;
    /**
     * Condition
     */
    condition: string;
    /**
     * Icon
     */
    icon: string;
};

/**
 * CalendarInsightsResponse
 */
export type CalendarInsightsResponse = {
    /**
     * Utilization Rate
     */
    utilization_rate: number;
    unworn_items_insight: UnwornItemsInsight;
    /**
     * Next 3 Days Forecast
     */
    next_3_days_forecast: Array<CalendarForecastDay>;
    weather_impact: WeatherImpact;
};

/**
 * CalendarScheduleRequest
 */
export type CalendarScheduleRequest = {
    /**
     * Date
     */
    date: string;
    /**
     * Outfit Id
     */
    outfit_id: number;
    /**
     * Event Name
     */
    event_name?: string | null;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Image Url
     */
    image_url?: string | null;
};

/**
 * ChatMessageFeedbackRequest
 */
export type ChatMessageFeedbackRequest = {
    /**
     * Message Id
     */
    message_id: number;
    /**
     * Rating
     */
    rating: string;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * ChatMessageResponse
 */
export type ChatMessageResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Suggested Outfit Id
     */
    suggested_outfit_id?: number | null;
    /**
     * Rating
     */
    rating?: string | null;
    /**
     * Feedback Comment
     */
    feedback_comment?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClosetSummaryResponse
 */
export type ClosetSummaryResponse = {
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Favorites Count
     */
    favorites_count: number;
    /**
     * Category Counts
     */
    category_counts: {
        [key: string]: number;
    };
    /**
     * Color Distribution
     */
    color_distribution: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ClothingItemDetailResponse
 */
export type ClothingItemDetailResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Color Name
     */
    color_name?: string | null;
    /**
     * Color Code
     */
    color_code: string;
    /**
     * Style
     */
    style: string;
    /**
     * Image Url
     */
    image_url: string;
    stats: ClothingItemDetailStats;
    /**
     * Pairs Well With
     */
    pairs_well_with: Array<ClothingItemFlat>;
    /**
     * Ai Styling Note
     */
    ai_styling_note: string;
};

/**
 * ClothingItemDetailStats
 */
export type ClothingItemDetailStats = {
    /**
     * Worn Count This Month
     */
    worn_count_this_month: number;
    /**
     * Versatility Score
     */
    versatility_score: number;
    /**
     * Matching Items Count
     */
    matching_items_count: number;
};

/**
 * ClothingItemFlat
 */
export type ClothingItemFlat = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Color Name
     */
    color_name?: string | null;
    /**
     * Color Code
     */
    color_code: string;
    /**
     * Style
     */
    style?: string | null;
    /**
     * Style Tag
     */
    style_tag?: string | null;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Is Ai Fixed
     */
    is_ai_fixed?: boolean | null;
};

/**
 * ColorHarmonyGuide
 */
export type ColorHarmonyGuide = {
    /**
     * Harmony Type
     */
    harmony_type: string;
    /**
     * Description
     */
    description: string;
    /**
     * Color Wheel Tip
     */
    color_wheel_tip: string;
    /**
     * Recommended Combinations
     */
    recommended_combinations: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ColorTheoryResponse
 */
export type ColorTheoryResponse = {
    /**
     * Guides
     */
    guides: Array<ColorHarmonyGuide>;
    /**
     * Ai Advice
     */
    ai_advice: string;
};

/**
 * DashboardResponse
 */
export type DashboardResponse = {
    /**
     * Location
     */
    location: string;
    weather: WeatherBlock;
    /**
     * Schedule
     */
    schedule: string;
    /**
     * Recommended Outfits
     */
    recommended_outfits: Array<OutfitRecommendation>;
};

/**
 * ExploreTrendsResponse
 */
export type ExploreTrendsResponse = {
    /**
     * Season Lookbooks
     */
    season_lookbooks: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Trend Articles
     */
    trend_articles: Array<TrendArticle>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemUpdateRequest
 */
export type ItemUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Color Name
     */
    color_name?: string | null;
    /**
     * Color Code
     */
    color_code?: string | null;
    /**
     * Style Tag
     */
    style_tag?: string | null;
};

/**
 * LookItem
 */
export type LookItem = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Occasion
     */
    occasion: string;
};

/**
 * OfflineSyncRequest
 */
export type OfflineSyncRequest = {
    /**
     * Outfit Id
     */
    outfit_id: number;
    /**
     * Event Title
     */
    event_title?: string | null;
    /**
     * Local Timestamp
     */
    local_timestamp: string;
};

/**
 * OutfitByEventRequest
 */
export type OutfitByEventRequest = {
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Weather Condition
     */
    weather_condition?: string | null;
};

/**
 * OutfitCreateRequest
 */
export type OutfitCreateRequest = {
    /**
     * Style Type
     */
    style_type?: string | null;
    /**
     * Item Ids
     */
    item_ids: Array<number>;
};

/**
 * OutfitFromItemsRequest
 */
export type OutfitFromItemsRequest = {
    /**
     * Item Ids
     */
    item_ids: Array<number>;
    /**
     * Event
     */
    event?: string | null;
    /**
     * Weather
     */
    weather?: string | null;
};

/**
 * OutfitRecommendation
 */
export type OutfitRecommendation = {
    /**
     * Outfit Id
     */
    outfit_id: number;
    /**
     * Style Type
     */
    style_type: string;
    /**
     * Items
     */
    items: Array<ClothingItemFlat>;
};

/**
 * OutfitUpdateRequest
 */
export type OutfitUpdateRequest = {
    /**
     * Style Type
     */
    style_type?: string | null;
    /**
     * Item Ids
     */
    item_ids?: Array<number> | null;
};

/**
 * ScanInitiateResponse
 */
export type ScanInitiateResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * StyleInsightsResponse
 */
export type StyleInsightsResponse = {
    /**
     * Utilization Rate
     */
    utilization_rate: number;
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Items Worn This Month
     */
    items_worn_this_month: number;
    /**
     * Top Style
     */
    top_style: string;
};

/**
 * StyleSuggestionResponse
 */
export type StyleSuggestionResponse = {
    /**
     * Preferred Style
     */
    preferred_style: Array<string>;
    /**
     * Style Analysis
     */
    style_analysis: string;
    /**
     * Style Tips
     */
    style_tips: Array<string>;
    /**
     * Recommended Looks
     */
    recommended_looks: Array<LookItem>;
    /**
     * Suggested Additions
     */
    suggested_additions: Array<string>;
};

/**
 * SwapOutfitItemRequest
 */
export type SwapOutfitItemRequest = {
    /**
     * Old Item Id
     */
    old_item_id: number;
    /**
     * New Item Id
     */
    new_item_id: number;
};

/**
 * TaskStatusResponse
 */
export type TaskStatusResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Progress Message
     */
    progress_message?: string | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * TrendArticle
 */
export type TrendArticle = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Season
     */
    season: string;
    /**
     * Read Time
     */
    read_time: string;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Content
     */
    content: string;
    /**
     * Tags
     */
    tags: Array<string>;
};

/**
 * UnwornItemsInsight
 */
export type UnwornItemsInsight = {
    /**
     * Count
     */
    count: number;
    /**
     * Threshold Days
     */
    threshold_days: number;
    /**
     * Message
     */
    message: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Preferred Style
     */
    preferred_style?: Array<string>;
};

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Preferred Style
     */
    preferred_style?: Array<string> | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Preferred Style
     */
    preferred_style: Array<string>;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WeatherBlock
 */
export type WeatherBlock = {
    /**
     * Condition
     */
    condition: string;
    /**
     * Temperature
     */
    temperature: number;
    /**
     * Recommendation
     */
    recommendation: string;
};

/**
 * WeatherImpact
 */
export type WeatherImpact = {
    /**
     * Level
     */
    level: string;
    /**
     * Recommendation Summary
     */
    recommendation_summary: string;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProfileApiV1AuthProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/profile';
};

export type GetProfileApiV1AuthProfileGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetProfileApiV1AuthProfileGetResponse = GetProfileApiV1AuthProfileGetResponses[keyof GetProfileApiV1AuthProfileGetResponses];

export type UpdateProfileApiV1AuthProfilePutData = {
    body: UserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/profile';
};

export type UpdateProfileApiV1AuthProfilePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileApiV1AuthProfilePutError = UpdateProfileApiV1AuthProfilePutErrors[keyof UpdateProfileApiV1AuthProfilePutErrors];

export type UpdateProfileApiV1AuthProfilePutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateProfileApiV1AuthProfilePutResponse = UpdateProfileApiV1AuthProfilePutResponses[keyof UpdateProfileApiV1AuthProfilePutResponses];

export type UploadAvatarApiV1AuthProfileAvatarPostData = {
    body: BodyUploadAvatarApiV1AuthProfileAvatarPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/profile/avatar';
};

export type UploadAvatarApiV1AuthProfileAvatarPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadAvatarApiV1AuthProfileAvatarPostError = UploadAvatarApiV1AuthProfileAvatarPostErrors[keyof UploadAvatarApiV1AuthProfileAvatarPostErrors];

export type UploadAvatarApiV1AuthProfileAvatarPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UploadAvatarApiV1AuthProfileAvatarPostResponse = UploadAvatarApiV1AuthProfileAvatarPostResponses[keyof UploadAvatarApiV1AuthProfileAvatarPostResponses];

export type ChangePasswordApiV1AuthChangePasswordPostData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/change-password';
};

export type ChangePasswordApiV1AuthChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1AuthChangePasswordPostError = ChangePasswordApiV1AuthChangePasswordPostErrors[keyof ChangePasswordApiV1AuthChangePasswordPostErrors];

export type ChangePasswordApiV1AuthChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScanClothingCameraApiV1ClosetScanPostData = {
    body: BodyScanClothingCameraApiV1ClosetScanPost;
    path?: never;
    query?: never;
    url: '/api/v1/closet/scan';
};

export type ScanClothingCameraApiV1ClosetScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanClothingCameraApiV1ClosetScanPostError = ScanClothingCameraApiV1ClosetScanPostErrors[keyof ScanClothingCameraApiV1ClosetScanPostErrors];

export type ScanClothingCameraApiV1ClosetScanPostResponses = {
    /**
     * Successful Response
     */
    200: ScanInitiateResponse;
};

export type ScanClothingCameraApiV1ClosetScanPostResponse = ScanClothingCameraApiV1ClosetScanPostResponses[keyof ScanClothingCameraApiV1ClosetScanPostResponses];

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/closet/scan/status/{task_id}';
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetError = GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors[keyof GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors];

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskStatusResponse;
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponse = GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses[keyof GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses];

export type ApproveAndSaveItemApiV1ClosetSavePostData = {
    body: ApproveAndSaveRequest;
    path?: never;
    query?: never;
    url: '/api/v1/closet/save';
};

export type ApproveAndSaveItemApiV1ClosetSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveAndSaveItemApiV1ClosetSavePostError = ApproveAndSaveItemApiV1ClosetSavePostErrors[keyof ApproveAndSaveItemApiV1ClosetSavePostErrors];

export type ApproveAndSaveItemApiV1ClosetSavePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetMyWardrobeApiV1ClosetItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: string;
        /**
         * Style
         */
        style?: string | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/closet/items';
};

export type GetMyWardrobeApiV1ClosetItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyWardrobeApiV1ClosetItemsGetError = GetMyWardrobeApiV1ClosetItemsGetErrors[keyof GetMyWardrobeApiV1ClosetItemsGetErrors];

export type GetMyWardrobeApiV1ClosetItemsGetResponses = {
    /**
     * Response Get My Wardrobe Api V1 Closet Items Get
     *
     * Successful Response
     */
    200: Array<ClothingItemFlat>;
};

export type GetMyWardrobeApiV1ClosetItemsGetResponse = GetMyWardrobeApiV1ClosetItemsGetResponses[keyof GetMyWardrobeApiV1ClosetItemsGetResponses];

export type DeleteClothingItemApiV1ClosetItemsItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/closet/items/{item_id}';
};

export type DeleteClothingItemApiV1ClosetItemsItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClothingItemApiV1ClosetItemsItemIdDeleteError = DeleteClothingItemApiV1ClosetItemsItemIdDeleteErrors[keyof DeleteClothingItemApiV1ClosetItemsItemIdDeleteErrors];

export type DeleteClothingItemApiV1ClosetItemsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetItemDetailApiV1ClosetItemsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/closet/items/{item_id}';
};

export type GetItemDetailApiV1ClosetItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemDetailApiV1ClosetItemsItemIdGetError = GetItemDetailApiV1ClosetItemsItemIdGetErrors[keyof GetItemDetailApiV1ClosetItemsItemIdGetErrors];

export type GetItemDetailApiV1ClosetItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ClothingItemDetailResponse;
};

export type GetItemDetailApiV1ClosetItemsItemIdGetResponse = GetItemDetailApiV1ClosetItemsItemIdGetResponses[keyof GetItemDetailApiV1ClosetItemsItemIdGetResponses];

export type UpdateClothingItemApiV1ClosetItemsItemIdPutData = {
    body: ItemUpdateRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/closet/items/{item_id}';
};

export type UpdateClothingItemApiV1ClosetItemsItemIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClothingItemApiV1ClosetItemsItemIdPutError = UpdateClothingItemApiV1ClosetItemsItemIdPutErrors[keyof UpdateClothingItemApiV1ClosetItemsItemIdPutErrors];

export type UpdateClothingItemApiV1ClosetItemsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: ClothingItemFlat;
};

export type UpdateClothingItemApiV1ClosetItemsItemIdPutResponse = UpdateClothingItemApiV1ClosetItemsItemIdPutResponses[keyof UpdateClothingItemApiV1ClosetItemsItemIdPutResponses];

export type ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/closet/items/{item_id}/favorite';
};

export type ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostError = ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostErrors[keyof ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostErrors];

export type ToggleFavoriteItemApiV1ClosetItemsItemIdFavoritePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyOutfitsApiV1ClosetOutfitsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Bookmarked Only
         */
        bookmarked_only?: boolean;
    };
    url: '/api/v1/closet/outfits';
};

export type GetMyOutfitsApiV1ClosetOutfitsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyOutfitsApiV1ClosetOutfitsGetError = GetMyOutfitsApiV1ClosetOutfitsGetErrors[keyof GetMyOutfitsApiV1ClosetOutfitsGetErrors];

export type GetMyOutfitsApiV1ClosetOutfitsGetResponses = {
    /**
     * Response Get My Outfits Api V1 Closet Outfits Get
     *
     * Successful Response
     */
    200: Array<OutfitRecommendation>;
};

export type GetMyOutfitsApiV1ClosetOutfitsGetResponse = GetMyOutfitsApiV1ClosetOutfitsGetResponses[keyof GetMyOutfitsApiV1ClosetOutfitsGetResponses];

export type CreateCustomOutfitApiV1ClosetOutfitsPostData = {
    body: OutfitCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/closet/outfits';
};

export type CreateCustomOutfitApiV1ClosetOutfitsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomOutfitApiV1ClosetOutfitsPostError = CreateCustomOutfitApiV1ClosetOutfitsPostErrors[keyof CreateCustomOutfitApiV1ClosetOutfitsPostErrors];

export type CreateCustomOutfitApiV1ClosetOutfitsPostResponses = {
    /**
     * Successful Response
     */
    201: OutfitRecommendation;
};

export type CreateCustomOutfitApiV1ClosetOutfitsPostResponse = CreateCustomOutfitApiV1ClosetOutfitsPostResponses[keyof CreateCustomOutfitApiV1ClosetOutfitsPostResponses];

export type ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostData = {
    body?: never;
    path: {
        /**
         * Outfit Id
         */
        outfit_id: number;
    };
    query?: never;
    url: '/api/v1/closet/outfits/{outfit_id}/bookmark';
};

export type ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostError = ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostErrors[keyof ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostErrors];

export type ToggleBookmarkOutfitApiV1ClosetOutfitsOutfitIdBookmarkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteData = {
    body?: never;
    path: {
        /**
         * Outfit Id
         */
        outfit_id: number;
    };
    query?: never;
    url: '/api/v1/closet/outfits/{outfit_id}';
};

export type DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteError = DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteErrors[keyof DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteErrors];

export type DeleteCustomOutfitApiV1ClosetOutfitsOutfitIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutData = {
    body: OutfitUpdateRequest;
    path: {
        /**
         * Outfit Id
         */
        outfit_id: number;
    };
    query?: never;
    url: '/api/v1/closet/outfits/{outfit_id}';
};

export type UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutError = UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutErrors[keyof UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutErrors];

export type UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutResponses = {
    /**
     * Successful Response
     */
    200: OutfitRecommendation;
};

export type UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutResponse = UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutResponses[keyof UpdateCustomOutfitApiV1ClosetOutfitsOutfitIdPutResponses];

export type UploadClothingItemImageApiV1ClosetItemsUploadPostData = {
    body: BodyUploadClothingItemImageApiV1ClosetItemsUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/closet/items/upload';
};

export type UploadClothingItemImageApiV1ClosetItemsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadClothingItemImageApiV1ClosetItemsUploadPostError = UploadClothingItemImageApiV1ClosetItemsUploadPostErrors[keyof UploadClothingItemImageApiV1ClosetItemsUploadPostErrors];

export type UploadClothingItemImageApiV1ClosetItemsUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetClosetSummaryApiV1ClosetSummaryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/closet/summary';
};

export type GetClosetSummaryApiV1ClosetSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: ClosetSummaryResponse;
};

export type GetClosetSummaryApiV1ClosetSummaryGetResponse = GetClosetSummaryApiV1ClosetSummaryGetResponses[keyof GetClosetSummaryApiV1ClosetSummaryGetResponses];

export type GetItemPairingsApiV1ClosetItemsItemIdPairingsGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/api/v1/closet/items/{item_id}/pairings';
};

export type GetItemPairingsApiV1ClosetItemsItemIdPairingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemPairingsApiV1ClosetItemsItemIdPairingsGetError = GetItemPairingsApiV1ClosetItemsItemIdPairingsGetErrors[keyof GetItemPairingsApiV1ClosetItemsItemIdPairingsGetErrors];

export type GetItemPairingsApiV1ClosetItemsItemIdPairingsGetResponses = {
    /**
     * Response Get Item Pairings Api V1 Closet Items  Item Id  Pairings Get
     *
     * Successful Response
     */
    200: Array<ClothingItemFlat>;
};

export type GetItemPairingsApiV1ClosetItemsItemIdPairingsGetResponse = GetItemPairingsApiV1ClosetItemsItemIdPairingsGetResponses[keyof GetItemPairingsApiV1ClosetItemsItemIdPairingsGetResponses];

export type TestAiConnectionApiV1AiTestConnectionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/test-connection';
};

export type TestAiConnectionApiV1AiTestConnectionGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/style-suggestions';
};

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses = {
    /**
     * Successful Response
     */
    200: StyleSuggestionResponse;
};

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponse = GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses[keyof GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses];

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostData = {
    body: OutfitFromItemsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/outfit-from-items';
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostError = GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors[keyof GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors];

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses = {
    /**
     * Response Get Outfit From Items Api V1 Ai Outfit From Items Post
     *
     * Successful Response
     */
    200: Array<OutfitRecommendation>;
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponse = GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses[keyof GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses];

export type GetOutfitByEventApiV1AiOutfitByEventPostData = {
    body: OutfitByEventRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/outfit-by-event';
};

export type GetOutfitByEventApiV1AiOutfitByEventPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOutfitByEventApiV1AiOutfitByEventPostError = GetOutfitByEventApiV1AiOutfitByEventPostErrors[keyof GetOutfitByEventApiV1AiOutfitByEventPostErrors];

export type GetOutfitByEventApiV1AiOutfitByEventPostResponses = {
    /**
     * Successful Response
     */
    200: OutfitRecommendation;
};

export type GetOutfitByEventApiV1AiOutfitByEventPostResponse = GetOutfitByEventApiV1AiOutfitByEventPostResponses[keyof GetOutfitByEventApiV1AiOutfitByEventPostResponses];

export type ChatAndModifyOutfitApiV1AiChatPostData = {
    body: AiChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat';
};

export type ChatAndModifyOutfitApiV1AiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatAndModifyOutfitApiV1AiChatPostError = ChatAndModifyOutfitApiV1AiChatPostErrors[keyof ChatAndModifyOutfitApiV1AiChatPostErrors];

export type ChatAndModifyOutfitApiV1AiChatPostResponses = {
    /**
     * Successful Response
     */
    200: AiChatResponse;
};

export type ChatAndModifyOutfitApiV1AiChatPostResponse = ChatAndModifyOutfitApiV1AiChatPostResponses[keyof ChatAndModifyOutfitApiV1AiChatPostResponses];

export type ClearChatHistoryApiV1AiChatHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat/history';
};

export type ClearChatHistoryApiV1AiChatHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChatHistoryApiV1AiChatHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat/history';
};

export type GetChatHistoryApiV1AiChatHistoryGetResponses = {
    /**
     * Response Get Chat History Api V1 Ai Chat History Get
     *
     * Successful Response
     */
    200: Array<ChatMessageResponse>;
};

export type GetChatHistoryApiV1AiChatHistoryGetResponse = GetChatHistoryApiV1AiChatHistoryGetResponses[keyof GetChatHistoryApiV1AiChatHistoryGetResponses];

export type SubmitChatFeedbackApiV1AiChatFeedbackPostData = {
    body: ChatMessageFeedbackRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat/feedback';
};

export type SubmitChatFeedbackApiV1AiChatFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitChatFeedbackApiV1AiChatFeedbackPostError = SubmitChatFeedbackApiV1AiChatFeedbackPostErrors[keyof SubmitChatFeedbackApiV1AiChatFeedbackPostErrors];

export type SubmitChatFeedbackApiV1AiChatFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHomeDashboardApiV1DashboardHomeGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lat
         */
        lat: number;
        /**
         * Lon
         */
        lon: number;
    };
    url: '/api/v1/dashboard/home';
};

export type GetHomeDashboardApiV1DashboardHomeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHomeDashboardApiV1DashboardHomeGetError = GetHomeDashboardApiV1DashboardHomeGetErrors[keyof GetHomeDashboardApiV1DashboardHomeGetErrors];

export type GetHomeDashboardApiV1DashboardHomeGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardResponse;
};

export type GetHomeDashboardApiV1DashboardHomeGetResponse = GetHomeDashboardApiV1DashboardHomeGetResponses[keyof GetHomeDashboardApiV1DashboardHomeGetResponses];

export type WearOutfitApiV1DashboardWearOutfitPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Outfit Id
         */
        outfit_id: number;
        /**
         * Event Title
         */
        event_title?: string;
        /**
         * Weather Status
         */
        weather_status?: string;
    };
    url: '/api/v1/dashboard/wear-outfit';
};

export type WearOutfitApiV1DashboardWearOutfitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WearOutfitApiV1DashboardWearOutfitPostError = WearOutfitApiV1DashboardWearOutfitPostErrors[keyof WearOutfitApiV1DashboardWearOutfitPostErrors];

export type WearOutfitApiV1DashboardWearOutfitPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Category
         */
        category: string;
    };
    url: '/api/v1/dashboard/swap-alternatives';
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetError = GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors[keyof GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors];

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses = {
    /**
     * Response Get Swap Alternatives Api V1 Dashboard Swap Alternatives Get
     *
     * Successful Response
     */
    200: Array<ClothingItemFlat>;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponse = GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses[keyof GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses];

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/calendar/weekly';
};

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses = {
    /**
     * Response Get Weekly Calendar Strip Api V1 Dashboard Calendar Weekly Get
     *
     * Successful Response
     */
    200: Array<CalendarDayPreview>;
};

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponse = GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses[keyof GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses];

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/insights';
};

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses = {
    /**
     * Successful Response
     */
    200: StyleInsightsResponse;
};

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponse = GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses[keyof GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses];

export type GetCalendarInsightsApiV1DashboardCalendarInsightsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/calendar/insights';
};

export type GetCalendarInsightsApiV1DashboardCalendarInsightsGetResponses = {
    /**
     * Successful Response
     */
    200: CalendarInsightsResponse;
};

export type GetCalendarInsightsApiV1DashboardCalendarInsightsGetResponse = GetCalendarInsightsApiV1DashboardCalendarInsightsGetResponses[keyof GetCalendarInsightsApiV1DashboardCalendarInsightsGetResponses];

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData = {
    /**
     * Actions
     */
    body: Array<OfflineSyncRequest>;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/sync-offline-history';
};

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostError = SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors[keyof SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors];

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCalendarByRangeApiV1DashboardCalendarGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/api/v1/dashboard/calendar';
};

export type GetCalendarByRangeApiV1DashboardCalendarGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCalendarByRangeApiV1DashboardCalendarGetError = GetCalendarByRangeApiV1DashboardCalendarGetErrors[keyof GetCalendarByRangeApiV1DashboardCalendarGetErrors];

export type GetCalendarByRangeApiV1DashboardCalendarGetResponses = {
    /**
     * Response Get Calendar By Range Api V1 Dashboard Calendar Get
     *
     * Successful Response
     */
    200: Array<CalendarDayPreview>;
};

export type GetCalendarByRangeApiV1DashboardCalendarGetResponse = GetCalendarByRangeApiV1DashboardCalendarGetResponses[keyof GetCalendarByRangeApiV1DashboardCalendarGetResponses];

export type DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteData = {
    body?: never;
    path: {
        /**
         * History Id
         */
        history_id: number;
    };
    query?: never;
    url: '/api/v1/dashboard/calendar/{history_id}';
};

export type DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteError = DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteErrors[keyof DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteErrors];

export type DeleteCalendarHistoryApiV1DashboardCalendarHistoryIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostData = {
    body: SwapOutfitItemRequest;
    path: {
        /**
         * Outfit Id
         */
        outfit_id: number;
    };
    query?: never;
    url: '/api/v1/dashboard/outfit/{outfit_id}/swap';
};

export type SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostError = SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostErrors[keyof SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostErrors];

export type SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostResponses = {
    /**
     * Successful Response
     */
    200: OutfitRecommendation;
};

export type SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostResponse = SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostResponses[keyof SwapOutfitItemApiV1DashboardOutfitOutfitIdSwapPostResponses];

export type ScheduleCalendarEventApiV1DashboardCalendarSchedulePostData = {
    body: CalendarScheduleRequest;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/calendar/schedule';
};

export type ScheduleCalendarEventApiV1DashboardCalendarSchedulePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduleCalendarEventApiV1DashboardCalendarSchedulePostError = ScheduleCalendarEventApiV1DashboardCalendarSchedulePostErrors[keyof ScheduleCalendarEventApiV1DashboardCalendarSchedulePostErrors];

export type ScheduleCalendarEventApiV1DashboardCalendarSchedulePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUpcomingCalendarEventsApiV1DashboardCalendarEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/calendar/events';
};

export type GetUpcomingCalendarEventsApiV1DashboardCalendarEventsGetResponses = {
    /**
     * Response Get Upcoming Calendar Events Api V1 Dashboard Calendar Events Get
     *
     * Successful Response
     */
    200: Array<CalendarDayPreview>;
};

export type GetUpcomingCalendarEventsApiV1DashboardCalendarEventsGetResponse = GetUpcomingCalendarEventsApiV1DashboardCalendarEventsGetResponses[keyof GetUpcomingCalendarEventsApiV1DashboardCalendarEventsGetResponses];

export type GetFashionTrendsApiV1ExploreTrendsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/explore/trends';
};

export type GetFashionTrendsApiV1ExploreTrendsGetResponses = {
    /**
     * Successful Response
     */
    200: ExploreTrendsResponse;
};

export type GetFashionTrendsApiV1ExploreTrendsGetResponse = GetFashionTrendsApiV1ExploreTrendsGetResponses[keyof GetFashionTrendsApiV1ExploreTrendsGetResponses];

export type GetColorTheoryGuidesApiV1ExploreColorTheoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/explore/color-theory';
};

export type GetColorTheoryGuidesApiV1ExploreColorTheoryGetResponses = {
    /**
     * Successful Response
     */
    200: ColorTheoryResponse;
};

export type GetColorTheoryGuidesApiV1ExploreColorTheoryGetResponse = GetColorTheoryGuidesApiV1ExploreColorTheoryGetResponses[keyof GetColorTheoryGuidesApiV1ExploreColorTheoryGetResponses];

export type GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: number;
    };
    query?: never;
    url: '/api/v1/explore/trends/{article_id}';
};

export type GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetError = GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetErrors[keyof GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetErrors];

export type GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetResponses = {
    /**
     * Successful Response
     */
    200: TrendArticle;
};

export type GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetResponse = GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetResponses[keyof GetTrendArticleDetailApiV1ExploreTrendsArticleIdGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
