// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * AIChatRequest
 */
export type AiChatRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * History
     */
    history?: Array<ChatMessage> | null;
    /**
     * Current Outfit Id
     */
    current_outfit_id?: number | null;
    /**
     * Event
     */
    event?: string | null;
    /**
     * Weather
     */
    weather?: string | null;
};

/**
 * AIChatResponse
 */
export type AiChatResponse = {
    /**
     * Reply
     */
    reply: string;
    suggested_outfit?: OutfitRecommendation | null;
};

/**
 * ApproveAndSaveRequest
 */
export type ApproveAndSaveRequest = {
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Category
     */
    category: string;
    /**
     * Color Code
     */
    color_code: string;
    /**
     * Style Tag
     */
    style_tag: string;
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_scan_clothing_camera_api_v1_closet_scan_post
 */
export type BodyScanClothingCameraApiV1ClosetScanPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CalendarDayPreview
 */
export type CalendarDayPreview = {
    /**
     * Date
     */
    date: string;
    /**
     * Day Name
     */
    day_name: string;
    /**
     * Is Highlighted
     */
    is_highlighted: boolean;
    /**
     * Event Title
     */
    event_title?: string | null;
    outfit?: OutfitRecommendation | null;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Image Url
     */
    image_url?: string | null;
};

/**
 * ClothingItemFlat
 */
export type ClothingItemFlat = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Color Code
     */
    color_code: string;
    /**
     * Style Tag
     */
    style_tag: string;
};

/**
 * DashboardResponse
 */
export type DashboardResponse = {
    /**
     * Location
     */
    location: string;
    weather: WeatherBlock;
    /**
     * Schedule
     */
    schedule: string;
    /**
     * Recommended Outfits
     */
    recommended_outfits: Array<OutfitRecommendation>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LookItem
 */
export type LookItem = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Occasion
     */
    occasion: string;
};

/**
 * OfflineSyncRequest
 */
export type OfflineSyncRequest = {
    /**
     * Outfit Id
     */
    outfit_id: number;
    /**
     * Event Title
     */
    event_title?: string | null;
    /**
     * Local Timestamp
     */
    local_timestamp: string;
};

/**
 * OutfitFromItemsRequest
 */
export type OutfitFromItemsRequest = {
    /**
     * Item Ids
     */
    item_ids: Array<number>;
    /**
     * Event
     */
    event?: string | null;
    /**
     * Weather
     */
    weather?: string | null;
};

/**
 * OutfitRecommendation
 */
export type OutfitRecommendation = {
    /**
     * Outfit Id
     */
    outfit_id: number;
    /**
     * Style Type
     */
    style_type: string;
    /**
     * Items
     */
    items: Array<ClothingItemFlat>;
};

/**
 * ScanInitiateResponse
 */
export type ScanInitiateResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * StyleInsightsResponse
 */
export type StyleInsightsResponse = {
    /**
     * Utilization Rate
     */
    utilization_rate: number;
    /**
     * Total Items
     */
    total_items: number;
    /**
     * Items Worn This Month
     */
    items_worn_this_month: number;
    /**
     * Top Style
     */
    top_style: string;
};

/**
 * StyleSuggestionResponse
 */
export type StyleSuggestionResponse = {
    /**
     * Preferred Style
     */
    preferred_style: Array<string>;
    /**
     * Style Analysis
     */
    style_analysis: string;
    /**
     * Style Tips
     */
    style_tips: Array<string>;
    /**
     * Recommended Looks
     */
    recommended_looks: Array<LookItem>;
    /**
     * Suggested Additions
     */
    suggested_additions: Array<string>;
};

/**
 * TaskStatusResponse
 */
export type TaskStatusResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * State
     */
    state: string;
    /**
     * Progress Message
     */
    progress_message?: string | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Preferred Style
     */
    preferred_style?: Array<string>;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Preferred Style
     */
    preferred_style: Array<string>;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WeatherBlock
 */
export type WeatherBlock = {
    /**
     * Condition
     */
    condition: string;
    /**
     * Temperature
     */
    temperature: number;
    /**
     * Recommendation
     */
    recommendation: string;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetHomeDashboardApiV1DashboardHomeGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lat
         */
        lat: number;
        /**
         * Lon
         */
        lon: number;
    };
    url: '/api/v1/dashboard/home';
};

export type GetHomeDashboardApiV1DashboardHomeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHomeDashboardApiV1DashboardHomeGetError = GetHomeDashboardApiV1DashboardHomeGetErrors[keyof GetHomeDashboardApiV1DashboardHomeGetErrors];

export type GetHomeDashboardApiV1DashboardHomeGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardResponse;
};

export type GetHomeDashboardApiV1DashboardHomeGetResponse = GetHomeDashboardApiV1DashboardHomeGetResponses[keyof GetHomeDashboardApiV1DashboardHomeGetResponses];

export type WearOutfitApiV1DashboardWearOutfitPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Outfit Id
         */
        outfit_id: number;
        /**
         * Event Title
         */
        event_title?: string;
        /**
         * Weather Status
         */
        weather_status?: string;
    };
    url: '/api/v1/dashboard/wear-outfit';
};

export type WearOutfitApiV1DashboardWearOutfitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WearOutfitApiV1DashboardWearOutfitPostError = WearOutfitApiV1DashboardWearOutfitPostErrors[keyof WearOutfitApiV1DashboardWearOutfitPostErrors];

export type WearOutfitApiV1DashboardWearOutfitPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Category
         */
        category: string;
    };
    url: '/api/v1/dashboard/swap-alternatives';
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetError = GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors[keyof GetSwapAlternativesApiV1DashboardSwapAlternativesGetErrors];

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses = {
    /**
     * Response Get Swap Alternatives Api V1 Dashboard Swap Alternatives Get
     *
     * Successful Response
     */
    200: Array<ClothingItemFlat>;
};

export type GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponse = GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses[keyof GetSwapAlternativesApiV1DashboardSwapAlternativesGetResponses];

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/calendar/weekly';
};

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses = {
    /**
     * Response Get Weekly Calendar Strip Api V1 Dashboard Calendar Weekly Get
     *
     * Successful Response
     */
    200: Array<CalendarDayPreview>;
};

export type GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponse = GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses[keyof GetWeeklyCalendarStripApiV1DashboardCalendarWeeklyGetResponses];

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/insights';
};

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses = {
    /**
     * Successful Response
     */
    200: StyleInsightsResponse;
};

export type GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponse = GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses[keyof GetWardrobeStyleInsightsApiV1DashboardInsightsGetResponses];

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostData = {
    /**
     * Actions
     */
    body: Array<OfflineSyncRequest>;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/sync-offline-history';
};

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostError = SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors[keyof SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostErrors];

export type SyncOfflineHistoryApiV1DashboardSyncOfflineHistoryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScanClothingCameraApiV1ClosetScanPostData = {
    body: BodyScanClothingCameraApiV1ClosetScanPost;
    path?: never;
    query?: never;
    url: '/api/v1/closet/scan';
};

export type ScanClothingCameraApiV1ClosetScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanClothingCameraApiV1ClosetScanPostError = ScanClothingCameraApiV1ClosetScanPostErrors[keyof ScanClothingCameraApiV1ClosetScanPostErrors];

export type ScanClothingCameraApiV1ClosetScanPostResponses = {
    /**
     * Successful Response
     */
    200: ScanInitiateResponse;
};

export type ScanClothingCameraApiV1ClosetScanPostResponse = ScanClothingCameraApiV1ClosetScanPostResponses[keyof ScanClothingCameraApiV1ClosetScanPostResponses];

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/closet/scan/status/{task_id}';
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetError = GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors[keyof GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetErrors];

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskStatusResponse;
};

export type GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponse = GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses[keyof GetScanTaskStatusApiV1ClosetScanStatusTaskIdGetResponses];

export type ApproveAndSaveItemApiV1ClosetSavePostData = {
    body: ApproveAndSaveRequest;
    path?: never;
    query?: never;
    url: '/api/v1/closet/save';
};

export type ApproveAndSaveItemApiV1ClosetSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveAndSaveItemApiV1ClosetSavePostError = ApproveAndSaveItemApiV1ClosetSavePostErrors[keyof ApproveAndSaveItemApiV1ClosetSavePostErrors];

export type ApproveAndSaveItemApiV1ClosetSavePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetMyWardrobeApiV1ClosetItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/closet/items';
};

export type GetMyWardrobeApiV1ClosetItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyWardrobeApiV1ClosetItemsGetError = GetMyWardrobeApiV1ClosetItemsGetErrors[keyof GetMyWardrobeApiV1ClosetItemsGetErrors];

export type GetMyWardrobeApiV1ClosetItemsGetResponses = {
    /**
     * Response Get My Wardrobe Api V1 Closet Items Get
     *
     * Successful Response
     */
    200: Array<ClothingItemFlat>;
};

export type GetMyWardrobeApiV1ClosetItemsGetResponse = GetMyWardrobeApiV1ClosetItemsGetResponses[keyof GetMyWardrobeApiV1ClosetItemsGetResponses];

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/style-suggestions';
};

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses = {
    /**
     * Successful Response
     */
    200: StyleSuggestionResponse;
};

export type GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponse = GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses[keyof GetStyleSuggestionsApiV1AiStyleSuggestionsGetResponses];

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostData = {
    body: OutfitFromItemsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/outfit-from-items';
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostError = GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors[keyof GetOutfitFromItemsApiV1AiOutfitFromItemsPostErrors];

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses = {
    /**
     * Response Get Outfit From Items Api V1 Ai Outfit From Items Post
     *
     * Successful Response
     */
    200: Array<OutfitRecommendation>;
};

export type GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponse = GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses[keyof GetOutfitFromItemsApiV1AiOutfitFromItemsPostResponses];

export type ChatAndModifyOutfitApiV1AiChatPostData = {
    body: AiChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat';
};

export type ChatAndModifyOutfitApiV1AiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatAndModifyOutfitApiV1AiChatPostError = ChatAndModifyOutfitApiV1AiChatPostErrors[keyof ChatAndModifyOutfitApiV1AiChatPostErrors];

export type ChatAndModifyOutfitApiV1AiChatPostResponses = {
    /**
     * Successful Response
     */
    200: AiChatResponse;
};

export type ChatAndModifyOutfitApiV1AiChatPostResponse = ChatAndModifyOutfitApiV1AiChatPostResponses[keyof ChatAndModifyOutfitApiV1AiChatPostResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
